### ISSUE TITLE
Survival Analysis exercise question

### ISSUE THREAD

**Issue by jonashera** [keithmcnulty/peopleanalytics-regression-book#13]
Hi Keith,

In the book (chapter 9) you define the main event as "left" and you say it is 1 for someone who left and 0 for someone who stayed. Then at the chart you call this metric "retention rate". and 1 means "retained" while 0 means "left". How did you define the Y axis as being the retention rate?

I want to do a similar analysis for my company focusing on Promotions and analyze promotion rates in the last 3 years by adding diversity variables in the model. I am defining 1 is someone was promoted and 0 if not. Does it mean that in the chart my Y axis will show the "Probability of not getting a promotion"?

Thank you
Jona

**Comment by keithmcnulty** [comment]
Hi Jona.  In my presentation, the hazard event is attrition,  so an employee is labelled 1 if they left in a given month and 0 if they did not.  When we plot Kaplan-Meier survival curves, we use a formula to calculate how many events occurred in a given month, which gives us a 'hazard rate' and then we subtract that hazard rate from 1 to get a 'survival rate' or in this case a 'retention rate'.  So survival is the opposite of hazard.

When we run a Cox proportional hazard model we are modelling the hazard, so that tells us about the likelihood of someone leaving. 

If your hazard event is promotion, then your default survival curves will represent (1 - promotion rate) which is the rate of non-promotion.  To make this more intuitive you can always subtract your survival rates from 1 and this will give you a promotion rate.  It can be a bit mind bending to think about modeling a positive event as a hazard.  I include an example of this in the Chapter 12 exercises in the print/kindle book.

Hope that helps!

Hope that helps.

**Comment by jonashera** [comment]
Thank you Keith for your quick reply and for taking the time to explain. This helps a lot. Also thank you for making this book publicly available. I've been building my career in People Analytics in the last 3 years and this book is extremely helpful in content for me, and I believe also for many other people in the field.

Looking forward to more content. 
Best!
Jona
