### ISSUE TITLE
7.1.3 Difference Between Datasets

### ISSUE THREAD

**Issue by aliaamiri** [keithmcnulty/peopleanalytics-regression-book#16]
It seems the `soccer` dataset within `peopleanalyticsdata` library is a bit different from the csv file. 

![Soccer_dataset](https://user-images.githubusercontent.com/91113291/140770555-09ff6b12-03a6-4972-b264-39e5a391b7aa.PNG)

**Comment by keithmcnulty** [comment]
This is because the the datasets in the library are RDS files and so the can be saved with appropriate data types, making it more convenient for the reader to work with them in R.  If the reader chooses to import data from the online CSVs they will need to do the type conversion themselves as per some of the instruction in the book.  Thanks!

**Comment by aliaamiri** [comment]
Thank you very much. I got the point.
