### ISSUE TITLE
Chapter 4 Questions & Solutions

### ISSUE THREAD

**Issue by cjoanc27** [keithmcnulty/peopleanalytics-regression-book#21]
Sharing my attempts on the data exercises for everyone's review, along with a few questions (beginner's level warning):

- I experienced some cut-off of my codes when I knit them together to a PDF document - the long codes would just not wrap themselves per the page layout width unless I did it manually. I tried a couple of suggestions online but failed - any suggestions?

- I treated`family_size` as an integer data type, and a continuous variable in the model - do we treat predictor variables in integer just as continuous variables or dummy code them as needed? Or it depends?

- For residual analysis (10), I plotted residuals against fitted values in my model but residuals appear to follow some "clustering" with a lack of continuity against the predicted values? This seems to align with my true-against-fitted plot, where predicted values stayed "flat" over a range of true values. Any explanation on that? Is it because `annual_income_ppp` is bit skewed or `average_wk_hrs` shows a somewhat binomial distribution? 

[Chapter 4.pdf](https://github.com/keithmcnulty/peopleanalytics-regression-book/files/8056540/Chapter.4.pdf)

**Comment by keithmcnulty** [comment]
Hi Jo

1.  There are options in R Markdown to control how code is handled in code boxes and you can find these in the great R Markdown book I reference in Chapter 2.  However, any lines of code that go beyond a certain length are not likely to be following good code style principles and I would encourage you to try to learn and keep to style principles in your code.   Well styled code is unlikely to be long enough to be cut off.  Tidyverse style principles are as good as any (https://style.tidyverse.org/)
2. Generally a variable should be treated as categorical if there are a limited number of categories and where it is not possible for the variable to take a value outside of those categories.   Family size can be a wide range of values and there is in theory no maximum. (Although in practice there is of a course a maximum).   So integer is the right way to treat this. Generally you see that categorical variables with order to them start to behave statistically like integers in a model once they have more than a few levels.  
3.   Yes this would relate to the distribution of important predictor variables.  I don’t see any major skew in the residual plot so it’s not something I would worry about.  I’d describe average_wk_hours as bimodal rather than binomial.  

Hope that helps.   Thanks for sending these in!

**Comment by cjoanc27** [comment]
Hi Keith, 
Thanks much for the response - this is very helpful. 

In case anyone else needs it, the R Markdown reference book talked about the control of text width for pdf outputs in Chapter 5. The solution, however, would need the creation of an external LaTex file, which to my understanding would require other languages and software. 

I would perhaps start with the package`styler` to style codes and be rid of the cut-offs.
[https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html](url)
