### ISSUE TITLE
Chapter 7 Solutions 

### ISSUE THREAD

**Issue by cjoanc27** [keithmcnulty/peopleanalytics-regression-book#24]
For the tests of goodness-of-fit, I had contradicting results from lipsitz test (p = 0.3685) and Pulkstenis-Robinson test (p = 0.0325) on my simplified model.  Would you care to give a diagnosis?

```
generalhoslem::lipsitz.test(model2)
cats <- c("manager_hire", "high_hours_flag")
generalhoslem::pulkrob.chisq(model2, catvars = cats)
```

[Chapter 7.pdf](https://github.com/keithmcnulty/peopleanalytics-regression-book/files/8459862/Chapter.7.pdf)

**Comment by keithmcnulty** [comment]
Hi Jo,

This is an interesting example because it really shows the kinds of messy data/models that we have to deal with in practice.  There is an interesting paper comparing the different goodness-of-fit tests here: https://journals.sagepub.com/doi/pdf/10.1177/1536867X1701700308

In general Lipsitz is better at indicating poor fit for continuous input variables  PR for categorical input variables.  In the case of your model the majority of the variables are continuous so the fact that Lipsitz does not reject a good fit is positive support for a meaningful model.  That said, the model is not great, as we can see from the various pseudo-R^2 statistics.  It's only possible scratching at the edges of some causality here, and much of the question of manager performance remains unexplained by this data.

Hope that helps!

Keith

**Comment by cjoanc27** [comment]
Thanks, Keith - this is helpful.
