### ISSUE TITLE
Chapter 7 Data exercise 10

### ISSUE THREAD

**Issue by KTowndoc15** [keithmcnulty/peopleanalytics-regression-book#8]
Hello,

I was finishing up on the data exercise for Chapter 7 and I was wondering how to address two things in a report. 

The Pseudo R^2 that I have for my simplified model has ranges from .08 to .15 and an AIC of 920. I was wondering if would be appropriate or necessary to address this lower end (but still acceptable) of R^2? I.e. would it be important to call out here that there are clearly other things affecting a manager's performance group that have not been accounted for in this model to a non-statistics person? Are there general R^2 ranges that you go by?

And then, my AIC increased in my simplified model -- unclear if that was an indicator that I removed something that I shouldn't have -- or if it was a negligible change. 

Thanks so much, finding this all very helpful!

**Comment by keithmcnulty** [comment]
Hi there and glad you are working through the exercises!

In practice, the low Pseudo-R^2 has no bearing on the specific insights about which input variables relate to the outcome.  However, you have rightly noted that it does tell you that the input variables in this data set only explain a small proportion of the variance in manager performance.  This is not surprising because manager performance is likely a complex construct that is affected my many measurable and immeasurable factors, and indeed the outcome itself is not a great measure because it suffers from central tendency bias (whereby the majority of ratings are middle ratings).  I think this makes this example a really good one in that it reflects many of the challenges and nuances of data in people analytics.

If I were presenting this to management I would **double emphasize** that the insights that you are sharing only explain a small proportion of manager performance, because the danger is that people can get excited and carried away with new insights and they catch fire in the organization and suddenly become 'the key differentiator of manager performance' and then you have lost control of the message.  I would start and end any presentation with this caveat.

Regarding the AIC, as you know a higher AIC means greater information loss.  If you remove two variables and you lose a tiny bit of information (eg your AIC goes from 920 to 930 or something), you may regard that as acceptable in return for the simplicity of the new model, especially if the variables you are losing are not even close to being significant. That is the human judgment that underlies the concept of model parsimony.  You may also wish to play with the `MASS::stepAIC()` function which uses an automated process to reduce the model to a more parsimonious form.  You can see what that function comes up with and compare it to your simplified model version.  

Hope that helps!

**Comment by KTowndoc15** [comment]
Very helpful! I have witnessed first hand many times(and probably
contributed to unfortunately in a few) the "carried away" and "key
differentiator" factor in my prior org. Actually I work with Pippa Rom --
well I did prior to Dec 31st -- and she's a good friend; and I believe she
was a colleague of yours as well.

Thanks again -- can't tell you how helpful and timely this has been. Having
all of this so relevant to people analytics and in one place is amazing.

Kristen Robinson
